import { useState, useEffect } from 'react'
import {
  Zap, RefreshCw, CheckCircle2, AlertCircle,
  Clock, Database, ArrowRight, Wand2,
  Building2, Calculator, BarChart3, Layers,
  Play, Loader2, ChevronRight, Download,
  Eye, X, Activity
} from 'lucide-react'
import { useProjectStore } from '@/store/useProjectStore'
import { useAuthStore } from '@/store/useAuthStore'
import { useBridgeStore } from '@/store/useBridgeStore'
import { useTemplateStore } from '@/store/useTemplateStore'
import { useReportStore } from '@/store/useReportStore'
import { autoGenerateReports, calcAutomationLevel, type AutoGenResult } from '@/bridge/autoGenEngine'
import type { SourceApp } from '@/bridge/bridgeTypes'
import { timeAgo } from '@/lib/utils'

// ─── Source app display config ────────────────────────────────────

const APP_CONFIG: Record<SourceApp, {
  label: string; icon: React.ElementType
  color: string; bg: string; border: string
  dataKey: keyof import('@/bridge/bridgeTypes').EcosystemData
}> = {
  structural: {
    label: 'CivilOS Structural', icon: Calculator,
    color: 'text-blue-700', bg: 'bg-blue-50', border: 'border-blue-200',
    dataKey: 'structural',
  },
  estimate: {
    label: 'CivilOS Estimate', icon: BarChart3,
    color: 'text-green-700', bg: 'bg-green-50', border: 'border-green-200',
    dataKey: 'estimate',
  },
  'project-management': {
    label: 'CivilOS Project Mgmt', icon: Activity,
    color: 'text-purple-700', bg: 'bg-purple-50', border: 'border-purple-200',
    dataKey: 'projectManagement',
  },
  architectural: {
    label: 'CivilOS Design', icon: Building2,
    color: 'text-amber-700', bg: 'bg-amber-50', border: 'border-amber-200',
    dataKey: 'architectural',
  },
}

export default function BridgePage() {
  const { user } = useAuthStore()
  const { currentProject } = useProjectStore()
  const { templates, fetchTemplates } = useTemplateStore()
  const { createReport } = useReportStore()
  const {
    ecosystem, loading, seeding, error,
    fetchAll, subscribe, unsubscribeAll, seedDemo,
  } = useBridgeStore()

  const [generating, setGenerating]       = useState(false)
  const [genResults, setGenResults]       = useState<AutoGenResult[]>([])
  const [showResults, setShowResults]     = useState(false)
  const [savingAll, setSavingAll]         = useState(false)
  const [savedCount, setSavedCount]       = useState(0)
  const [previewResult, setPreviewResult] = useState<AutoGenResult | null>(null)

  // Init
  useEffect(() => {
    if (!currentProject || !user) return
    fetchAll(currentProject.id)
    subscribe(currentProject.id)
    fetchTemplates(user.uid)
    return () => unsubscribeAll()
  }, [currentProject?.id])

  const automationInfo = ecosystem
    ? calcAutomationLevel(ecosystem)
    : { level: 0, connectedApps: 0, totalApps: 4, breakdown: [] }

  // ── Auto-generate all reports ──────────────────────────────────
  const handleAutoGenerate = async () => {
    if (!currentProject || !ecosystem) return
    setGenerating(true)
    setGenResults([])
    setShowResults(false)

    await new Promise((r) => setTimeout(r, 600)) // simulate processing

    const tplData = templates.map((t) => ({
      type: t.type, content: t.content, name: t.name,
    }))
    const results = autoGenerateReports(currentProject, ecosystem, tplData)
    setGenResults(results)
    setShowResults(true)
    setGenerating(false)
  }

  // ── Save all successful reports to Firestore ───────────────────
  const handleSaveAll = async () => {
    if (!currentProject || !user) return
    setSavingAll(true)
    let count = 0

    for (const result of genResults.filter((r) => r.status === 'success')) {
      await createReport({
        projectId: currentProject.id,
        type: result.reportType as never,
        title: result.title,
        status: 'draft',
        revision: 'Rev 00',
        generatedBy: user.email ?? 'Auto-generated',
        data: {
          compiledContent: result.content,
          autoGenerated: true,
          dataUsed: result.dataUsed,
        },
      })
      count++
    }

    setSavedCount(count)
    setSavingAll(false)
  }

  // ── Seed demo data ─────────────────────────────────────────────
  const handleSeedDemo = async () => {
    if (!currentProject) return
    await seedDemo(currentProject.id, currentProject.name)
  }

  const successCount  = genResults.filter((r) => r.status === 'success').length
  const skippedCount  = genResults.filter((r) => r.status === 'skipped').length
  const errorCount    = genResults.filter((r) => r.status === 'error').length

  return (
    <div className="animate-fade-in">

      {/* ── Header ── */}
      <div className="page-header flex items-start justify-between">
        <div>
          <h1 className="page-title">Ecosystem Bridge</h1>
          <p className="page-subtitle">
            {currentProject
              ? `${currentProject.name} · Auto-sync from all CivilOS apps`
              : 'Select a project to connect apps'}
          </p>
        </div>
        <div className="flex items-center gap-2">
          {currentProject && (
            <button
              onClick={() => fetchAll(currentProject.id)}
              disabled={loading}
              className="btn-secondary text-xs"
            >
              {loading
                ? <Loader2 size={13} className="animate-spin" />
                : <RefreshCw size={13} />
              }
              Refresh
            </button>
          )}
          <button
            onClick={handleAutoGenerate}
            disabled={!ecosystem || generating || !currentProject}
            className="btn-primary"
          >
            {generating
              ? <><Loader2 size={14} className="animate-spin" /> Generating...</>
              : <><Wand2 size={14} /> Auto-Generate All</>
            }
          </button>
        </div>
      </div>

      {!currentProject ? (
        <div className="card border-amber-200 bg-amber-50 flex items-center gap-3">
          <AlertCircle size={18} className="text-amber-500 shrink-0" />
          <p className="text-sm text-amber-700">Select a project from <strong>Projects</strong> to use the Bridge.</p>
        </div>
      ) : (
        <>
          {/* ── Automation Level Bar ── */}
          <div className="card mb-6">
            <div className="flex items-center justify-between mb-3">
              <div>
                <h2 className="text-sm font-display font-bold text-slate-900">Automation Level</h2>
                <p className="text-xs text-slate-400 mt-0.5">
                  {automationInfo.connectedApps}/{automationInfo.totalApps} apps connected
                </p>
              </div>
              <div className="text-right">
                <span className="text-3xl font-display font-bold text-primary-600">
                  {automationInfo.level}%
                </span>
                <p className="text-xs text-slate-400">automation</p>
              </div>
            </div>

            {/* Big progress bar */}
            <div className="h-3 bg-slate-100 rounded-full overflow-hidden mb-3">
              <div
                className={`h-full rounded-full transition-all duration-700 ${
                  automationInfo.level >= 80 ? 'bg-green-500' :
                  automationInfo.level >= 50 ? 'bg-blue-500' : 'bg-amber-500'
                }`}
                style={{ width: `${automationInfo.level}%` }}
              />
            </div>

            {/* Per-app contribution */}
            <div className="grid grid-cols-4 gap-2">
              {automationInfo.breakdown.map(({ app, connected, contribution }) => (
                <div
                  key={app}
                  className={`px-2 py-1.5 rounded-lg border text-center text-xs ${
                    connected ? 'bg-green-50 border-green-100 text-green-700' : 'bg-slate-50 border-slate-100 text-slate-400'
                  }`}
                >
                  <p className="font-semibold">{contribution}%</p>
                  <p className="text-[10px] mt-0.5 truncate">{app}</p>
                  {connected
                    ? <CheckCircle2 size={10} className="mx-auto mt-1 text-green-500" />
                    : <Clock size={10} className="mx-auto mt-1 text-slate-300" />
                  }
                </div>
              ))}
            </div>
          </div>

          {/* ── 4 App Status Cards ── */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
            {(Object.keys(APP_CONFIG) as SourceApp[]).map((app) => {
              const cfg      = APP_CONFIG[app]
              const Icon     = cfg.icon
              const status   = ecosystem?.syncStatus[app] ?? 'idle'
              const syncTime = ecosystem?.syncedAt[app]
              const data     = ecosystem?.[cfg.dataKey]
              const hasData  = Boolean(data)

              return (
                <div key={app} className={`card border-2 ${hasData ? cfg.border : 'border-slate-100'}`}>
                  <div className="flex items-start justify-between mb-3">
                    <div className={`w-9 h-9 rounded-xl border flex items-center justify-center ${
                      hasData ? `${cfg.bg} ${cfg.border}` : 'bg-slate-50 border-slate-100'
                    }`}>
                      <Icon size={16} className={hasData ? cfg.color : 'text-slate-300'} />
                    </div>
                    <StatusBadge status={status} hasData={hasData} />
                  </div>

                  <p className={`text-xs font-semibold mb-0.5 ${hasData ? 'text-slate-800' : 'text-slate-400'}`}>
                    {cfg.label}
                  </p>
                  <p className="text-[10px] text-slate-400">
                    {syncTime ? `Synced ${timeAgo(syncTime)}` : 'Not connected'}
                  </p>

                  {/* Data preview */}
                  {hasData && app === 'structural' && ecosystem?.structural && (
                    <div className="mt-2 space-y-0.5">
                      <DataPill label="Concrete" value={ecosystem.structural.concreteGrade} />
                      <DataPill label="Zone" value={ecosystem.structural.seismicZone} />
                      <DataPill label="SBC" value={`${ecosystem.structural.soilBearingCapacity} kN/m²`} />
                    </div>
                  )}
                  {hasData && app === 'estimate' && ecosystem?.estimate && (
                    <div className="mt-2 space-y-0.5">
                      <DataPill label="Total" value={`৳${(ecosystem.estimate.totalCost / 1e6).toFixed(1)}M`} />
                      <DataPill label="/m²" value={`৳${ecosystem.estimate.costPerSqm.toLocaleString()}`} />
                    </div>
                  )}
                  {hasData && app === 'project-management' && ecosystem?.projectManagement && (
                    <div className="mt-2 space-y-0.5">
                      <DataPill label="Done" value={`${ecosystem.projectManagement.overallCompletion}%`} />
                      <DataPill label="Phase" value={ecosystem.projectManagement.currentPhase} />
                    </div>
                  )}
                  {hasData && app === 'architectural' && ecosystem?.architectural && (
                    <div className="mt-2 space-y-0.5">
                      <DataPill label="FAR" value={`${ecosystem.architectural.far}`} />
                      <DataPill label="Coverage" value={`${ecosystem.architectural.groundCoverage}%`} />
                    </div>
                  )}
                </div>
              )
            })}
          </div>

          {/* ── Demo seed button ── */}
          {(!ecosystem?.structural && !ecosystem?.estimate) && (
            <div className="card border-dashed border-2 border-slate-200 mb-6 flex items-center justify-between p-5">
              <div>
                <p className="text-sm font-semibold text-slate-700">No data connected yet</p>
                <p className="text-xs text-slate-400 mt-0.5">
                  Load sample data to test the auto-generation engine
                </p>
              </div>
              <button
                onClick={handleSeedDemo}
                disabled={seeding}
                className="btn-primary shrink-0"
              >
                {seeding
                  ? <><Loader2 size={14} className="animate-spin" /> Loading...</>
                  : <><Database size={14} /> Load Demo Data</>
                }
              </button>
            </div>
          )}

          {/* ── Flow diagram ── */}
          <div className="card mb-6">
            <h2 className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-4">
              Automation Flow
            </h2>
            <div className="flex items-center gap-2 flex-wrap">
              {[
                { label: 'Architectural', color: 'bg-amber-100 text-amber-700 border-amber-200', connected: Boolean(ecosystem?.architectural) },
                { label: 'Structural',    color: 'bg-blue-100 text-blue-700 border-blue-200',    connected: Boolean(ecosystem?.structural) },
                { label: 'Estimate',      color: 'bg-green-100 text-green-700 border-green-200', connected: Boolean(ecosystem?.estimate) },
                { label: 'Project Mgmt', color: 'bg-purple-100 text-purple-700 border-purple-200',connected: Boolean(ecosystem?.projectManagement) },
              ].map(({ label, color, connected }, i, arr) => (
                <div key={label} className="flex items-center gap-2">
                  <div className={`px-3 py-1.5 rounded-lg border text-xs font-medium ${color} flex items-center gap-1.5 ${!connected ? 'opacity-40' : ''}`}>
                    {connected ? <CheckCircle2 size={11} /> : <Clock size={11} />}
                    {label}
                  </div>
                  {i < arr.length - 1 && <ArrowRight size={14} className="text-slate-300" />}
                </div>
              ))}
              <ArrowRight size={14} className="text-slate-300" />
              <div className="px-3 py-1.5 rounded-lg border border-primary-200 bg-primary-50 text-xs font-semibold text-primary-700 flex items-center gap-1.5">
                <Zap size={11} /> Reports App
              </div>
              <ArrowRight size={14} className="text-slate-300" />
              <div className="px-3 py-1.5 rounded-lg border border-slate-200 bg-slate-50 text-xs font-medium text-slate-600">
                PDF / XLSX / DOCX
              </div>
            </div>
          </div>

          {/* ── Generation Results ── */}
          {showResults && genResults.length > 0 && (
            <div className="card">
              <div className="flex items-center justify-between mb-4">
                <div>
                  <h2 className="text-sm font-display font-bold text-slate-900">Auto-Generation Results</h2>
                  <div className="flex items-center gap-3 mt-1">
                    <span className="text-xs text-green-600 font-medium">✓ {successCount} generated</span>
                    {skippedCount > 0 && <span className="text-xs text-amber-600">⊘ {skippedCount} skipped</span>}
                    {errorCount > 0 && <span className="text-xs text-red-600">✕ {errorCount} errors</span>}
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  {savedCount > 0 && (
                    <span className="text-xs text-green-600 font-medium">
                      <CheckCircle2 size={12} className="inline mr-1" />
                      {savedCount} saved to Reports
                    </span>
                  )}
                  {successCount > 0 && (
                    <button
                      onClick={handleSaveAll}
                      disabled={savingAll}
                      className="btn-primary text-xs py-1.5"
                    >
                      {savingAll
                        ? <><Loader2 size={12} className="animate-spin" /> Saving...</>
                        : <><Download size={12} /> Save All to Reports</>
                      }
                    </button>
                  )}
                  <button onClick={() => setShowResults(false)} className="btn-ghost p-1.5">
                    <X size={14} />
                  </button>
                </div>
              </div>

              <div className="space-y-2">
                {genResults.map((result) => (
                  <GenResultRow
                    key={result.reportType}
                    result={result}
                    onPreview={() => setPreviewResult(result)}
                  />
                ))}
              </div>
            </div>
          )}
        </>
      )}

      {/* ── Content Preview Modal ── */}
      {previewResult && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[85vh] flex flex-col">
            <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100">
              <h3 className="font-display font-bold text-slate-900">{previewResult.title}</h3>
              <button onClick={() => setPreviewResult(null)} className="btn-ghost p-1.5"><X size={16} /></button>
            </div>
            <div className="flex-1 overflow-y-auto p-6">
              <pre className="text-xs text-slate-700 font-mono whitespace-pre-wrap leading-relaxed bg-slate-50 rounded-xl p-4">
                {previewResult.content}
              </pre>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// ─── Sub-components ───────────────────────────────────────────────

function StatusBadge({ status, hasData }: { status: string; hasData: boolean }) {
  if (hasData) return (
    <span className="flex items-center gap-1 text-[10px] font-medium text-green-600">
      <span className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse-dot" />
      Synced
    </span>
  )
  if (status === 'error') return (
    <span className="flex items-center gap-1 text-[10px] font-medium text-red-500">
      <AlertCircle size={10} /> Error
    </span>
  )
  return (
    <span className="flex items-center gap-1 text-[10px] text-slate-400">
      <Clock size={10} /> Waiting
    </span>
  )
}

function DataPill({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between text-[10px]">
      <span className="text-slate-400">{label}</span>
      <span className="font-medium text-slate-600 truncate ml-2 max-w-[80px]">{value}</span>
    </div>
  )
}

function GenResultRow({ result, onPreview }: { result: AutoGenResult; onPreview: () => void }) {
  const isSuccess = result.status === 'success'
  const isSkipped = result.status === 'skipped'
  const isError   = result.status === 'error'

  return (
    <div className={`flex items-center gap-3 px-4 py-3 rounded-xl border ${
      isSuccess ? 'bg-green-50 border-green-100' :
      isSkipped ? 'bg-slate-50 border-slate-100' :
      'bg-red-50 border-red-100'
    }`}>
      {isSuccess && <CheckCircle2 size={15} className="text-green-500 shrink-0" />}
      {isSkipped && <Clock size={15} className="text-slate-400 shrink-0" />}
      {isError   && <AlertCircle size={15} className="text-red-500 shrink-0" />}

      <div className="flex-1 min-w-0">
        <p className={`text-sm font-medium ${isSuccess ? 'text-green-800' : isError ? 'text-red-700' : 'text-slate-600'}`}>
          {result.title}
        </p>
        {result.dataUsed.length > 0 && (
          <p className="text-[10px] text-slate-400 mt-0.5">
            Data from: {result.dataUsed.join(', ')}
          </p>
        )}
        {result.reason && (
          <p className="text-[10px] text-amber-600 mt-0.5">{result.reason}</p>
        )}
      </div>

      {isSuccess && (
        <button onClick={onPreview} className="btn-ghost text-xs py-1 px-2 shrink-0">
          <Eye size={12} /> Preview
        </button>
      )}
    </div>
  )
}
